name: Build Image
description: 构建一个镜像
labels:
- build image
body:
- type: markdown
  attributes:
    value: |
      # ↑↑↑↑↑↑↑↑↑↑↑ 填入你要构建的 Image名
      ## 请包含 名称:标签（可选 名称:标签,标签...） 示例：gpt:v1 fast:latest image_name:v1.0.0,v1.1.0,v2.0.0

- type: input
  attributes:
    label: 构建镜像密码
    placeholder: |
      # 请提供构建镜像的密码
  validations:
    required: true

- type: textarea
  attributes:
    label: 构建镜像DockerFile
    placeholder: |
      # 请提供构建镜像的DockerFile内容
  validations:
    required: true