name: Docker-Build

on:
  issues:
    types:
      - opened

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  issues: write


env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'build git image')
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Check Issue
      id: get-image
      env:
        IMAGE: "${{ github.event.issue.title }}"
      run: |
        ORIGIN_IMAGE="${IMAGE}"
        ISSUE_BODY="${{ github.event.issue.body }}"
        # 提取构建镜像密码
        BUILD_PASSWORD=$(echo "$ISSUE_BODY" | awk -F '\n' '/构建镜像密码/ {getline; getline; print $0}' | sed 's/^[[:space:]]*//')
        # echo "构建镜像密码: $BUILD_PASSWORD"
        # 提取构建镜像 GitUrl 内容
        BUILD_GITURL=$(echo "$ISSUE_BODY" | awk '/构建镜像Git链接/ {flag=1; next} flag {print}' | sed '1d' | sed 's/^[[:space:]]*//')
        echo "构建镜像 GitUrl 内容:"
        echo "$BUILD_GITURL"
        
        sudo chmod +x ./hack/verify.sh
        PASSWORD="$(./hack/verify.sh "${BUILD_PASSWORD}")"
        if [[ "${PASSWORD}" == "" ]]; then
        gh issue comment ${{ github.event.issue.number }} -b "构建镜像 '${ORIGIN_IMAGE}' 密码错误，请联系管理员"
        exit 1
        else
        NEW_ISSUE_BODY=$(echo "${{ github.event.issue.body }}" | awk -v password="${BUILD_PASSWORD}" '{gsub(password, "******"); print}')
        echo "新的issue内容: $NEW_ISSUE_BODY"
        gh issue edit ${{ github.event.issue.number }} --body "${NEW_ISSUE_BODY}"
        fi
        
        sudo chmod +x ./hack/supply-image.sh
        CORRECT_IMAGE="$(./hack/supply-image.sh "${ORIGIN_IMAGE}")"
        if [[ "${CORRECT_IMAGE}" == "" ]]; then
        gh issue comment ${{ github.event.issue.number }} -b "镜像 '${ORIGIN_IMAGE}' 名称不符合规范"
        exit 1
        fi
        
        cd /tmp
        mkdir git
        cd git
        # 尝试执行 git ls-remote 命令
        git ls-remote "$BUILD_GITURL" &> /dev/null
        # 获取命令的退出状态码
        EXIT_CODE=$?
        if [ $EXIT_CODE -eq 0 ]; then
        echo "Git 连接成功，可以正常访问远程仓库。"
        else
        echo "Git 连接失败，请检查网络、SSH 密钥或仓库 URL。"
        gh issue comment ${{ github.event.issue.number }} -b "链接 '${BUILD_GITURL}' 连接失败，请检查网络、SSH 密钥或仓库 URL。"
        exit 1
        fi
        git clone $BUILD_GITURL
        # 获取第一个子目录名
        FIRST_DIR=$(ls -d */ | head -n 1)
        # 去除目录名末尾的斜杠
        FIRST_DIR=${FIRST_DIR%/}
        echo "第一个子目录路径: /tmp/git/$FIRST_DIR"
        
        echo "image=${ORIGIN_IMAGE}" >> $GITHUB_OUTPUT
        echo "path=/tmp/git/$FIRST_DIR" >> $GITHUB_OUTPUT

    - name: Check Image
      run: |
        ORIGIN_IMAGE="${{ steps.get-image.outputs.image }}"
        gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 构建中...<br>[详情请查看](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"

    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    # 增加可用磁盘空间
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        # 如果空间还是不够用，可以把以下开启，清理出更多空间
        # remove-android: 'true'
        # remove-codeql: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image Aliyun
      id: build-image
      run: |
        ORIGIN_IMAGE="${{ steps.get-image.outputs.image }}"
        DOCKER_PATH="${{ steps.get-image.outputs.path }}"
        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
        # 数据预处理,判断镜像是否重名
        declare -A duplicate_images
        declare -A temp_map
        
        # 获取镜像名:版本号  例如nginx:1.25.3
        image_name_tag=${ORIGIN_IMAGE}
        echo "image_name_tag $image_name_tag"
        # 获取镜像名例如nginx
        image_name=$(echo "$image_name_tag" | awk -F':' '{print $1}')
        echo "image_name: $image_name"
        
        # 如果镜像存在于数组中，则添加temp_map
        if [[ -n "${temp_map[$image_name]}" ]]; then
            echo "duplicate image name: $image_name"
            duplicate_images[$image_name]="true"
        else
            # 存镜像的命名空间
            temp_map[$image_name]="fengmuxi"
        fi       
        
        cd $DOCKER_PATH
        echo "docker build -t ${ORIGIN_IMAGE} ."
        docker build -t ${ORIGIN_IMAGE} .
        # 将@sha256:等字符删除
        new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/${image_name_tag}"
        echo "docker tag $ORIGIN_IMAGE $new_image"
        docker tag $ORIGIN_IMAGE $new_image
        echo "docker push $new_image"
        docker push $new_image
        echo "开始清理磁盘空间"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
        docker rmi $ORIGIN_IMAGE
        docker rmi $new_image
        echo "磁盘空间清理完毕"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
        echo "image=${new_image}" >> $GITHUB_OUTPUT
        

    - name: Fail Build
      if: failure()
      run: |
        ORIGIN_IMAGE="${{ steps.get-image.outputs.image }}"
        gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 构建失败[详情请查看](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})<br>如有疑问请回复 /auto-cc 召唤帮助, 或者查看[构建成功案例](https://github.com/${{ github.repository }}/issues?q=is%3Aissue+is%3Aclosed+label%3A%22build+image+succeeded%22)"
        gh issue edit ${{ github.event.issue.number }} --add-label "build image failure" -b "IMAGE BUILD"
        gh issue close ${{ github.event.issue.number }} --reason "not planned"

    - name: Success Build
      if: success()
      run: |
        ORIGIN_IMAGE="${{ steps.get-image.outputs.image }}"
        DOCKER_IMAGE="${{ steps.build-image.outputs.image }}"
        gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 构建完成<br>请使用 $DOCKER_IMAGE 替代源镜像"
        gh issue edit ${{ github.event.issue.number }} --add-label "build image succeeded" -b "IMAGE BUILD"
        gh issue close ${{ github.event.issue.number }} --reason "completed"